"""§2.3 — 마이그레이션이 유일한 스키마 소스다.

`alembic check` 를 코드로 돌린다. 모델과 마이그레이션이 어긋나면 실패한다.
Phase 2 에서 첫 모델이 들어오는 순간부터 이 테스트가 일한다.
"""

import pytest
from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory
from alembic.util.exc import AutogenerateDiffsDetected

from app.core.paths import ALEMBIC_INI, MIGRATIONS_DIR


def _config(connection=None) -> Config:
    cfg = Config(str(ALEMBIC_INI))
    cfg.set_main_option('script_location', str(MIGRATIONS_DIR))
    if connection is not None:
        cfg.attributes['connection'] = connection
    return cfg


def test_migration_history_has_a_single_head():
    """머지 커밋에서 리비전이 갈라지면 배포가 조용히 반쪽만 적용된다."""
    heads = ScriptDirectory.from_config(_config()).get_heads()

    assert len(heads) == 1, f'alembic head 가 여러 개다: {heads}'


@pytest.mark.asyncio(loop_scope='session')
async def test_models_match_migrations(app, db_connection):
    """`alembic check` — 드리프트가 있으면 AutogenerateDiffsDetected 가 난다."""

    def _check(connection) -> None:
        command.check(_config(connection))

    try:
        await db_connection.run_sync(_check)
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - 실패 경로
        pytest.fail(f'모델과 마이그레이션이 어긋난다. `alembic revision --autogenerate` 를 실행해라.\n{exc}')


@pytest.mark.asyncio(loop_scope='session')
async def test_downgrade_to_base_and_back(app, db_connection):
    """리비전이 되돌릴 수 있는지 — downgrade 를 안 짜두면 롤백 배포에서 막힌다."""

    def _roundtrip(connection) -> None:
        cfg = _config(connection)
        command.downgrade(cfg, 'base')
        command.upgrade(cfg, 'head')

    await db_connection.run_sync(_roundtrip)
