"""add board and post tables

Revision ID: 25894f2c54bb
Revises: 8e5dfe6f8f03
Create Date: 2026-08-13 16:07:10.461476
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.common.db.types import UTCDateTime

revision: str = '25894f2c54bb'
down_revision: str | None = '8e5dfe6f8f03'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'board',
        sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
        sa.Column('created_at', UTCDateTime(), nullable=False),
        sa.Column('updated_at', UTCDateTime(), nullable=False),
        sa.Column('deleted', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), server_default='0', nullable=False),
        sa.Column('slug', sa.String(length=50), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('read_role', sa.String(length=50), nullable=False),
        sa.Column('write_role', sa.String(length=50), nullable=False),
        sa.Column('allow_comment', sa.Boolean(), nullable=False),
        sa.Column('allow_attachment', sa.Boolean(), nullable=False),
        sa.Column('display_order', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_board')),
        sa.UniqueConstraint('slug', 'deleted', name=op.f('uq_board_slug_deleted')),
    )
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_board_deleted'), ['deleted'], unique=False)

    op.create_table(
        'post',
        sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
        sa.Column('created_at', UTCDateTime(), nullable=False),
        sa.Column('updated_at', UTCDateTime(), nullable=False),
        sa.Column('deleted', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), server_default='0', nullable=False),
        sa.Column('board_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
        sa.Column('author_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('is_pinned', sa.Boolean(), nullable=False),
        sa.Column(
            'status', sa.Enum('draft', 'published', name='post_status', native_enum=False, length=20), nullable=False
        ),
        sa.Column('view_count', sa.Integer(), nullable=False),
        sa.Column('comment_count', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['author_id'], ['user.id'], name=op.f('fk_post_author_id_user')),
        sa.ForeignKeyConstraint(['board_id'], ['board.id'], name=op.f('fk_post_board_id_board')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_post')),
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index('ix_post_author', ['author_id', 'deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_deleted'), ['deleted'], unique=False)
        batch_op.create_index('ix_post_list', ['board_id', 'deleted', 'id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index('ix_post_list')
        batch_op.drop_index(batch_op.f('ix_post_deleted'))
        batch_op.drop_index('ix_post_author')

    op.drop_table('post')
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_board_deleted'))

    op.drop_table('board')
    # ### end Alembic commands ###
