"""add attachment table

Revision ID: 3f1804548b20
Revises: b22197a7663e
Create Date: 2026-08-14 10:32:21.844551
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.common.db.types import UTCDateTime

revision: str = '3f1804548b20'
down_revision: str | None = 'b22197a7663e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'attachment',
        sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
        sa.Column('created_at', UTCDateTime(), nullable=False),
        sa.Column('updated_at', UTCDateTime(), nullable=False),
        sa.Column('deleted', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), server_default='0', nullable=False),
        sa.Column('post_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
        sa.Column('author_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
        sa.Column('filename', sa.String(length=255), nullable=False),
        sa.Column('content_type', sa.String(length=100), nullable=False),
        sa.Column('size', sa.Integer(), nullable=False),
        sa.Column('storage_key', sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(['author_id'], ['user.id'], name=op.f('fk_attachment_author_id_user')),
        sa.ForeignKeyConstraint(['post_id'], ['post.id'], name=op.f('fk_attachment_post_id_post')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_attachment')),
    )
    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachment_deleted'), ['deleted'], unique=False)
        batch_op.create_index('ix_attachment_post', ['post_id', 'deleted'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.drop_index('ix_attachment_post')
        batch_op.drop_index(batch_op.f('ix_attachment_deleted'))

    op.drop_table('attachment')
    # ### end Alembic commands ###
