"""add user table

Revision ID: 8e5dfe6f8f03
Revises: 0001_baseline
Create Date: 2026-08-12 15:56:25.256795
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.common.db.types import UTCDateTime

revision: str = '8e5dfe6f8f03'
down_revision: str | None = '0001_baseline'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user',
        sa.Column('username', sa.String(length=50), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('nickname', sa.String(length=50), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column(
            'status', sa.Enum('active', 'locked', name='user_status', native_enum=False, length=20), nullable=False
        ),
        sa.Column('is_superuser', sa.Boolean(), nullable=False),
        sa.Column('last_login_at', UTCDateTime(), nullable=True),
        sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
        sa.Column('created_at', UTCDateTime(), nullable=False),
        sa.Column('updated_at', UTCDateTime(), nullable=False),
        sa.Column('deleted', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), server_default='0', nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
        sa.UniqueConstraint('email', 'deleted', name=op.f('uq_user_email_deleted')),
        sa.UniqueConstraint('username', 'deleted', name=op.f('uq_user_username_deleted')),
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_deleted'), ['deleted'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_deleted'))

    op.drop_table('user')
    # ### end Alembic commands ###
