"""add comment table

Revision ID: b22197a7663e
Revises: 25894f2c54bb
Create Date: 2026-08-13 16:43:48.250174
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.common.db.types import UTCDateTime

revision: str = 'b22197a7663e'
down_revision: str | None = '25894f2c54bb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'comment',
        sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
        sa.Column('created_at', UTCDateTime(), nullable=False),
        sa.Column('updated_at', UTCDateTime(), nullable=False),
        sa.Column('deleted', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), server_default='0', nullable=False),
        sa.Column('post_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
        sa.Column('author_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
        sa.Column('parent_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
        sa.Column('path', sa.String(length=64), nullable=False),
        sa.Column('depth', sa.Integer(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('is_removed', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['author_id'], ['user.id'], name=op.f('fk_comment_author_id_user')),
        sa.ForeignKeyConstraint(['parent_id'], ['comment.id'], name=op.f('fk_comment_parent_id_comment')),
        sa.ForeignKeyConstraint(['post_id'], ['post.id'], name=op.f('fk_comment_post_id_post')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_comment')),
    )
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_deleted'), ['deleted'], unique=False)
        batch_op.create_index('ix_comment_thread', ['post_id', 'path'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_index('ix_comment_thread')
        batch_op.drop_index(batch_op.f('ix_comment_deleted'))

    op.drop_table('comment')
    # ### end Alembic commands ###
